language: java
jdk:
  - openjdk8

branches: # 1.
  only:
    - main

# Travis CI 서버의 Home
cache: # 2.
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build" # 3.

# CI 실행 완료 시 메일 알람
notifications: # 4.
  email:
    recipients:
      - tahen922@naver.com
      - yerinyoon@ewhain.net
